---
title: "Practica 1"
author: "Cinthya Figueroa, Valeri Suarez, David Vidal"
date: "2024-01-10"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Science

### Pregunta 1

De las siguientes preguntas, clasifica cada una como descriptiva,
exploratoria, inferencia, predictiva o causal, y razona brevemente (una
frase) el por qué:

1.  Dado un registro de vehículos que circulan por una autopista,
    disponemos de su marca y modelo, país de matriculación, y tipo de
    vehículo (por número de ruedas). Con tal de ajustar precios de los
    peajes, ¿Cuántos vehículos tenemos por tipo? ¿Cuál es el tipo más
    frecuente? ¿De qué países tenemos más vehículos?

    **Respuesta:** Pregunta exploratoria. Porque se realiza un análisis
    de diversa información obtenida sobre los vehículos que circulan en
    una autopista.

2.  Dado un registro de visualizaciones de un servicio de
    video-on-demand, donde disponemos de los datos del usuario, de la
    película seleccionada, fecha de visualización y categoría de la
    película, queremos saber ¿Hay alguna preferencia en cuanto a género
    literario según los usuarios y su rango de edad?

    **Respuesta:** Pregunta descriptiva. Porque el conjunto de datos
    busca encontrar información.

3.  Dado un registro de peticiones a un sitio web, vemos que las
    peticiones que provienen de una red de telefonía concreta
    acostumbran a ser incorrectas y provocarnos errores de servicio.
    ¿Podemos determinar si en el futuro, los próximos mensajes de esa
    red seguirán dando problemas? ¿Hemos notado el mismo efecto en otras
    redes de telefonía?

    **Respuesta:** Pregunta predictiva. Porque se pretende hacer una
    predicción acerca del servicio de telefonía en un futuro.

4.  Dado los registros de usuarios de un servicio de compras por
    internet, los usuarios pueden agruparse por preferencias de
    productos comprados. Queremos saber si ¿Es posible que, dado un
    usuario al azar y según su historial, pueda ser directamente
    asignado a un o diversos grupos

    **Respuesta:** Pregunta inferencial. Porque la tendencia o el
    comportamiento de compras del usuario permite clasificarlo a un
    grupo o varios.

### Pregunta 2

Considera el siguiente escenario:

Sabemos que un usuario de nuestra red empresarial ha estado usando esta
para fines no relacionados con el trabajo, como por ejemplo tener un
servicio web no autorizado abierto a la red (otros usuarios tienen
servicios web activados y autorizados). No queremos tener que rastrear
los puertos de cada PC, y sabemos que la actividad puede haber cesado.
Pero podemos acceder a los registros de conexiones TCP de cada máquina
de cada trabajador (hacia donde abre conexión un PC concreto). Sabemos
que nuestros clientes se conectan desde lugares remotos de forma
legítima, como parte de nuestro negocio, y que un trabajador puede haber
habilitado temporalmente servicios de prueba. Nuestro objetivo es
reducir lo posible la lista de posibles culpables, con tal de
explicarles que por favor no expongan nuestros sistemas sin permiso de
los operadores o la dirección.

Explica con detalle cómo se podría proceder al análisis y resolución del
problema mediante Data Science, indicando de donde se obtendrían los
datos, qué tratamiento deberían recibir, qué preguntas hacerse para
resolver el problema, qué datos y gráficos se obtendrían, y cómo se
comunicarían estos.

**Respuesta:**

Problemática

-   ¿Que necesitamos saber/conocer?

-   ¿Cuál es el usuario culpable?

-   ¿Cómo lo hizo?

-   ¿Qué datos tenemos?

    -   Los registros de conexiones TCP de cada máquina de cada
        trabajador.

    -   Conocemos que clientes se conectan desde lugares remotos de
        forma legítima.

    -   Sabemos cuáles son los servicios legítimos que tenemos activos.

    -   Los puertos que se mantienen como lícitos para el uso de los
        servicios.

Acciones:

-   Explorar los datos que tenemos:
    -   Logs de cada máquina.
    -   Servicios y puertos permitidos.
    -   Listado de usuarios de la empresa.
    -   Dominios legítimos en los cuales se puede mantener comunicación.
-   Normalizar, adecuar o etiquetar los datos.
-   Comparar los servicios legítimos con los que estuvieron o están
    habilitados en los logs.
-   Comparar los puertos activos que están marcados como legítimos.
-   Ir generando una tabla con los usuarios cuya comparación indique que
    existió una violación de servicios.
-   Generar graficas que muestren las comparaciones antes mencionadas,
    en las cuales se debe visualizar los servicios y puertos ilegítimos.
-   Generar una gráfica que muestre la totalidad de los usuarios y el
    porcentaje de usuarios que hizo uso de servicios no autorizados.

Conclusiones y toma de decisiones según los resultados:

-   Analizar si el uso de esos servicios es realmente requerido para los
    usuarios.

-   Concientizar sobre el uso adecuado de las políticas establecidas en
    la organización.

-   Implementar políticas que bloqueen el uso tanto de puertos como de
    servicios ilegítimos.

## Introducción a R

Antes de proceder a resolver las preguntas, primero cargamos el archivo
haciendo uso del asistante visual de Rstudio, y con esta misma
herramienta separamos los datos en columnas y filas, y cambiamos el
formato de los datos a numérico en la ultima columna del documento
cargado.

Asignamos el nombre a las columnas con el siguiente código:

``` r
colnames (epa_http) <- c("IPs", "Timestamp", "Tipo", "URL", "Protocolo", "Código de respuesta", "Bytes")
```

### Pregunta 1

Una vez cargado el Dataset a analizar, comprobando que se cargan las
IPs, el Timestamp, la Petición (Tipo, URL y Protocolo), Código de
respuesta, y Bytes de reply.

1.  ¿Cuáles son las dimensiones del dataset cargado (número de filas y
    columnas)?

    Hacemos uso de la función dim y nos devolverá el valor exacto de
    filas y columnas.

    ``` r
    dim(epa_http)
    ```

    ``` r
    [1] 47748     7
    ```

2.  Valor medio de la columna Bytes

    Para poder realizar esta pregunta primero debemos asignar valores de
    0 a aquellas celdas que no tienen valores asignados en la columna
    Bytes

    ``` r
    epa_http$Bytes [is.na (epa_http$Bytes)] <- 0
    ```

    Después hacemos uso de la función mean y ya podemos obtener el valor
    medio.

    ``` r
    mean (epa_http$Bytes)
    ```

    ``` r
    [1] 6531.457
    ```

### Pregunta 2

De las diferentes IPs de origen accediendo al servidor, ¿Cuántas
pertenecen a una IP claramente educativa (que contenga ".edu")?

Para resolver esta pregunta utilizamos la función str_detect

``` r
sum (str_detect (epa_http$IPs, ".edu"))
```

``` r
[1] 6539
```

### Pregunta 3

De todas las peticiones recibidas por el servidor ¿Cuál es la hora en la
qué hay mayor volumen de peticiones HTTP de tipo "GET"?

Para resolver esta pregunta primero observamos que los datos están
almacenados en día, hora, minutos y segundos, así que para poder usar el
dato hora separamos los valores de Timestamp en varias columnas

``` r
epa_http <- epa_http %>% separate (Timestamp, paste0("Timestamp",1:4),sep=':')
```

Después eliminamos los corchetes en la columna Timestamp1 y Timestamp4 y
de la columna Tipo eliminamos las dobles comillas

``` r
epa_http$Timestamp1 <- str_replace( epa_http$Timestamp1, "\\[", "")
```

``` r
epa_http$Timestamp4 <- str_replace( epa_http$Timestamp4, "\\]", "")
```

``` r
epa_http$Tipo <- str_replace (epa_http$Tipo, "\"", "")
```

Creamos una condición que cumpla que si la petición es de tipo GET
almacene la hora en una nueva columna llamada Phoras.

``` r
epa_http$Phoras <- ifelse (str_equal ("GET", epa_http$Tipo) == TRUE, epa_http$Timestamp2, NA )
```

Creamos una nueva tabla y ahi almacenaremos las horas agrupadas y el
conteo de cuantas peticiones por hora se hacen

``` r
copy_epa <-epa_http %>% group_by(Phoras) %>% tally()
```

Finalmente buscamos en la nueva tabla creada cual es la hora en que
mayor volumen de peticiones se hace

``` r
Qhora <- copy_epa$Phoras [which.max (copy_epa$n)] 
print(Qhora)
```

``` r
[1] "14"
```

### Pregunta 4

De las peticiones hechas por instituciones educativas (.edu), ¿Cuantos
bytes en total se han transmitido, en peticiones de descarga de ficheros
de texto ".txt"?

Para resolver esta pregunta creamos una columna en donde se almacenaran
los valores de Bytes según se cumpla la condición

``` r
epa_http$compa <- ifelse((str_detect(epa_http$IPs, ".edu")) == TRUE & (str_detect(epa_http$URL, ".txt")) == TRUE, epa_http$Bytes, NA )
```

Cambiamos los valores NA a 0 para poder realizar la suma

``` r
epa_http$compa[is.na(epa_http$compa)] <- 0
```

Y finalmente sumamos todos los valores almacenados para encontrar el
total de bytes transmitidos

``` r
sum(epa_http$compa)
```

``` r
[1] 3017871
```

### Pregunta 5

Si separamos la petición en 3 partes (Tipo, URL, Protocolo), usando
str_split y el separador " " (espacio), ¿cuantas peticiones buscan
directamente la URL = "/"?

Realizamos la sumatoria de todos los casos en los cuales la columna URL
es igual "/" dado que que es a donde apunta la peticion.

``` r
sum(str_equal("/",epa_http$URL))
```

``` r
[1] 2382
```

### Pregunta 6

Aprovechando que hemos separado la petición en 3 partes (Tipo, URL,
Protocolo) ¿Cuantas peticiones NO tienen como protocolo "HTTP/0.2"?

Primero limpiamos la columna Protocolo y le eliminamos las dobles
comillas

``` r
epa_http$Protocolo <- str_replace(epa_http$Protocolo, "\"", "")
```

Realizamos la sumatoria de todas las peticiones donde no se uso el
protocolo HTTP/0.2 en la columna protocolo se añade el parametro ! para
que este tome todos los casos que sean diferentes al HTTP2.

``` r
sum(!str_equal("HTTP/0.2",epa_http$Protocolo))
```
